# Grafana Agent Configuration
# Acts as a bridge between the Python script and Mimir
# Accepts metrics via scraping a local pushgateway-style endpoint

server:
  log_level: info
  http_listen_port: 12345

metrics:
  wal_directory: /tmp/agent/wal
  global:
    scrape_interval: 5s
    external_labels:
      cluster: 'local-test'
      environment: 'development'
  
  configs:
    - name: default
      
      # Remote write to Mimir
      remote_write:
        - url: http://mimir:9009/api/v1/push
          headers:
            X-Scope-OrgID: anonymous
          queue_config:
            capacity: 10000
            max_shards: 10
            min_shards: 1
            max_samples_per_send: 5000
            batch_send_deadline: 5s
      
      # Scrape Pushgateway for metrics pushed by the script
      scrape_configs:
        - job_name: 'pushgateway'
          honor_labels: true
          honor_timestamps: true
          static_configs:
            - targets: ['pushgateway:9091']
        
        # Scrape self-metrics (agent monitoring)
        - job_name: 'agent'
          static_configs:
            - targets: ['localhost:12345']


