version: '3.8'

services:
  # Prometheus Pushgateway for testing metrics locally
  pushgateway:
    image: prom/pushgateway:latest
    ports:
      - "9091:9091"
    networks:
      - eval-network
  
  # AI Detector Evaluation Container
  ai-detector-eval:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # API Configuration
      - DETECTOR_API_URL=${DETECTOR_API_URL:-http://host.docker.internal:8000}
      - DETECTOR_API_TOKEN=${DETECTOR_API_TOKEN}
      
      # LLM Provider API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      
      # Prometheus
      - PUSHGATEWAY_URL=http://pushgateway:9091
      
      # Run Metadata
      - RUN_ID=${RUN_ID:-local-test}
      - DATASET_VERSION=${DATASET_VERSION:-v1.0}
      - GIT_COMMIT_SHA=${GIT_COMMIT_SHA:-local}
      
      # Output
      - OUTPUT_DIR=/tmp/output
    
    volumes:
      # Input data
      - ./sample_prompts.csv:/tmp/input/prompts.csv:ro
      
      # Output data
      - ./test_results:/tmp/output
    
    command: >
      --input /tmp/input/prompts.csv
      --generate-and-test
      --save-jsonl
      --save-manifest
      --output-dir /tmp/output
      --pushgateway-url http://pushgateway:9091
    
    networks:
      - eval-network
    
    depends_on:
      - pushgateway
    
    # Optional: Add resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G

networks:
  eval-network:
    driver: bridge
